// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/events": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/issues": {
    params: {};
  };
  "/api/issues/:id": {
    params: {
      "id": string;
    };
  };
  "/api/issues/:id/close": {
    params: {
      "id": string;
    };
  };
  "/api/issues/:id/comments": {
    params: {
      "id": string;
    };
  };
  "/api/deps": {
    params: {};
  };
  "/api/ready": {
    params: {};
  };
  "/api/stats": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/events" | "/api/health" | "/api/issues" | "/api/issues/:id" | "/api/issues/:id/close" | "/api/issues/:id/comments" | "/api/deps" | "/api/ready" | "/api/stats";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api.events.js": {
    id: "routes/api.events";
    page: "/api/events";
  };
  "routes/api.health.js": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.issues.js": {
    id: "routes/api.issues";
    page: "/api/issues";
  };
  "routes/api.issues.$id.js": {
    id: "routes/api.issues.$id";
    page: "/api/issues/:id";
  };
  "routes/api.issues.$id.close.js": {
    id: "routes/api.issues.$id.close";
    page: "/api/issues/:id/close";
  };
  "routes/api.issues.$id.comments.js": {
    id: "routes/api.issues.$id.comments";
    page: "/api/issues/:id/comments";
  };
  "routes/api.deps.js": {
    id: "routes/api.deps";
    page: "/api/deps";
  };
  "routes/api.ready.js": {
    id: "routes/api.ready";
    page: "/api/ready";
  };
  "routes/api.stats.js": {
    id: "routes/api.stats";
    page: "/api/stats";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/api.events": typeof import("./app/routes/api.events.js");
  "routes/api.health": typeof import("./app/routes/api.health.js");
  "routes/api.issues": typeof import("./app/routes/api.issues.js");
  "routes/api.issues.$id": typeof import("./app/routes/api.issues.$id.js");
  "routes/api.issues.$id.close": typeof import("./app/routes/api.issues.$id.close.js");
  "routes/api.issues.$id.comments": typeof import("./app/routes/api.issues.$id.comments.js");
  "routes/api.deps": typeof import("./app/routes/api.deps.js");
  "routes/api.ready": typeof import("./app/routes/api.ready.js");
  "routes/api.stats": typeof import("./app/routes/api.stats.js");
};